version: '3.8'
networks:
  keycloak-network:
    driver: bridge
services:
  postgres:
    image: postgres:latest
    container_name: keycloak-db
#    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - '5432:5432'
    networks:
      - keycloak-network
  keycloak:
    container_name: keycloak
    build:
      context: .
    #image: quay.io/keycloak/keycloak:19.0.1
    restart: unless-stopped
    environment:
      KC_HOSTNAME_STRICT: "false"
      KC_DB_URL: "jdbc:postgresql://postgres:5432"
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

    ports:
      - 8080:8080
      - 8443:8443
    networks:
      - keycloak-network
    depends_on:
      - postgres
